Feature/calls-data
ChidimmaOfodum/WM4--Final-Project--SlackDash pull request #19
Opened 2023-02-22 13:39 UTC by michellejanay

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-02-22 16:14 UTC, farzad-nazif requested changes

2023-02-22 16:14 UTC, farzad-nazif commented on server/api.js
> +router.get("/calls", getCalls);
Channel ID shouldn't be hardcoded using proccess.env.channel_id your API should accept a channel ID as params or query to that endpoint.

2023-02-22 17:37 UTC, michellejanay commented on server/api.js
> +router.get("/calls", getCalls);
Hi Farzad, 
Those changes will come later when we do the cohort level, this is just for the **channel** level. The goal this week was to get the data back from one channel.

2023-02-22 18:57 UTC, farzad-nazif approved these changes

2023-02-23 13:07 UTC, ChidimmaOfodum approved these changes

2023-02-23 13:07 UTC, merged